-- Popular cultivar expansion for catalog species with incomplete variety lists

INSERT INTO plant_catalog_variety (plant_catalog_id, name, description, sort_order)
SELECT c.id, v.name, v.description, v.sort_order
FROM plant_catalog c
JOIN (VALUES
  ('American Plum', 'Toka', 'Hybrid plum; sweet-tart', 4),
  ('American Plum', 'BlackIce', 'Dark skin dessert plum', 5),
  ('American Plum', 'Mount Royal', 'Blue European plum', 6),
  ('American Plum', 'Oppenheim', 'German freestone plum', 7),
  ('American Plum', 'Underwood', 'Early yellow plum', 8),
  ('Black Currant', 'Titania', 'Swedish cultivar; heavy crop', 4),
  ('Black Currant', 'Big Ben', 'Large sweet berries', 5),
  ('Black Currant', 'Minaj Smyriou', 'Mild sweet black currant', 6),
  ('Black Currant', 'Willoughby', 'American heavy producer', 7),
  ('Black Currant', 'Ben Connan', 'Compact; large fruit', 8),
  ('Bleeding Heart', 'Valentine', 'Red heart flowers', 4),
  ('Bleeding Heart', 'Burning Hearts', 'Deep red compact', 5),
  ('Bleeding Heart', 'King of Hearts', 'Fern-leaf red type', 6),
  ('Bleeding Heart', 'Luxuriant', 'Red fringed bleeding heart', 7),
  ('Bleeding Heart', 'Snowdrift', 'White fringed form', 8),
  ('Brandywine Tomato', 'Sudduth''s Strain', 'Large pink heirloom line', 4),
  ('Brandywine Tomato', 'OTV Brandywine', 'Orange heirloom Brandywine', 5),
  ('Brandywine Tomato', 'Potato Leaf', 'Potato-leaf Brandywine strain', 6),
  ('Brandywine Tomato', 'Ruth''s Perfect', 'Selected Brandywine line', 7),
  ('Brandywine Tomato', 'Black Brandywine', 'Dark heirloom Brandywine', 8),
  ('Chamomile', 'Bodegold', 'Double-flower tea chamomile', 4),
  ('Chamomile', 'Treneague', 'Non-flowering lawn chamomile', 5),
  ('Chamomile', 'Flore Pleno', 'Double Roman chamomile', 6),
  ('Chamomile', 'Egyptian', 'Strong tea chamomile', 7),
  ('Chamomile', 'Camo', 'Low mat chamomile', 8),
  ('Chives', 'Staro', 'Uniform thick leaves', 4),
  ('Chives', 'Forstar', 'Early heavy producer', 5),
  ('Chives', 'Polyvit', 'Commercial bunching type', 6),
  ('Chives', 'Nelly', 'Large leaf chives', 7),
  ('Chives', 'Profusion', 'Ornamental pink flowers', 8),
  ('Concord Grape', 'Mars', 'Seedless blue table grape', 4),
  ('Concord Grape', 'Somerset', 'Seedless red NE hardy', 5),
  ('Concord Grape', 'Interlaken', 'Seedless white early', 6),
  ('Concord Grape', 'Canadice', 'Seedless red slipskin', 7),
  ('Concord Grape', 'Glenora', 'Seedless blue early', 8),
  ('Fleabane', 'Pink Mist', 'Pink native fleabane', 4),
  ('Fleabane', 'Prosperity', 'Heavy blooming selection', 5),
  ('Fleabane', 'Daisy May', 'Compact white form', 6),
  ('Fleabane', 'Eastern Star', 'Native meadow selection', 7),
  ('Fleabane', 'Ann''s Choice', 'Low mounding fleabane', 8),
  ('French Tarragon', 'Russian Tarragon', 'Hardy but milder flavor', 4),
  ('French Tarragon', 'Mexican Mint Marigold', 'Warm-season tarragon substitute', 5),
  ('French Tarragon', 'Winter Tarragon', 'Tagetes lucida type', 6),
  ('French Tarragon', 'Dr. Higgs', 'Selected French clone', 7),
  ('French Tarragon', 'Classic Cuttings', 'Mother plant propagation', 8),
  ('Greek Oregano', 'Compactum', 'Low mounding habit', 4),
  ('Greek Oregano', 'Variegata', 'Gold-edge leaves', 5),
  ('Greek Oregano', 'Cleopatra', 'Compact Greek type', 6),
  ('Greek Oregano', 'Syriaca', 'Showy hops-type oregano', 7),
  ('Greek Oregano', 'Hot and Spicy', 'Peppery leaves', 8),
  ('Highbush Cranberry', 'Hahs', 'Heavy fruiting native', 4),
  ('Highbush Cranberry', 'Phillips', 'Selected American type', 5),
  ('Highbush Cranberry', 'Bailey Compact', 'Dwarf cranberry bush', 6),
  ('Highbush Cranberry', 'Alfredo', 'Large fruit clusters', 7),
  ('Highbush Cranberry', 'Redwing', 'Red fall foliage', 8),
  ('Lemon Balm', 'Aurea', 'Golden lemon balm', 4),
  ('Lemon Balm', 'Variegata', 'White-splashed leaves', 5),
  ('Lemon Balm', 'All Gold', 'Chartreuse foliage', 6),
  ('Lemon Balm', 'Lime', 'Lime-scented selection', 7),
  ('Lemon Balm', 'Lime Green', 'Bright chartreuse leaves', 8),
  ('Mullein', 'Challenger', 'Ornamental mullein', 4),
  ('Mullein', 'Southern Charm', 'Yellow spike hybrid', 5),
  ('Mullein', 'Giovanni Grass', 'Compact ornamental', 6),
  ('Mullein', 'Pink', 'Rare pink flowered mullein', 7),
  ('Mullein', 'Arabian Nights', 'Dark spike ornamental', 8),
  ('Ostrich Fern', 'Richie''s Giant', 'Large fiddleheads', 4),
  ('Ostrich Fern', 'Oregon', 'West coast fiddlehead type', 5),
  ('Ostrich Fern', 'Pictum', 'Variegated ostrich fern', 6),
  ('Ostrich Fern', 'Harris', 'Selected for harvest', 7),
  ('Ostrich Fern', 'Native Division', 'Local NE division', 8),
  ('Virginia Bluebell', 'Miles Standish', 'Pink bell selection', 4),
  ('Virginia Bluebell', 'Montrose Blue', 'Large blue flowers', 5),
  ('Virginia Bluebell', 'Marie', 'Compact blue form', 6),
  ('Virginia Bluebell', 'Bartram', 'Named native strain', 7),
  ('Virginia Bluebell', 'Rose Pink', 'Pink flowering clump', 8),
  ('Apple Tree', 'Empire', 'Balanced sweet-tart NE favorite', 11),
  ('Apple Tree', 'Northern Spy', 'Classic pie apple', 12),
  ('Apple Tree', 'Paula Red', 'Early tart apple', 13),
  ('Apple Tree', 'Jonathan', 'Spicy old-time apple', 14),
  ('Apple Tree', 'Ida Red', 'Crisp storage apple', 15),
  ('Apple Tree', 'Winesap', 'Aromatic heirloom', 16),
  ('Pear Tree', 'Harrows Sweet', 'Fire blight resistant', 7),
  ('Pear Tree', 'Kieffer', 'Hardy sand pear', 8),
  ('Pear Tree', 'Magness', 'Disease resistant dessert', 9),
  ('Pear Tree', 'Starkrimson', 'Red Bartlett sport', 10),
  ('Peach Tree', 'Bounty', 'Late season freestone', 7),
  ('Peach Tree', 'Gloria', 'White flesh heirloom', 8),
  ('Peach Tree', 'Intrepid', 'Cold-hardy late bloom', 9),
  ('Peach Tree', 'Madison', 'Hardy southern selection', 10),
  ('Grape Vine', 'Swenson Red', 'Cold-hardy table grape', 8),
  ('Grape Vine', 'Somerset Seedless', 'Seedless red NE grape', 9),
  ('Grape Vine', 'Brianna', 'White wine and table', 10),
  ('Grape Vine', 'La Crescent', 'White wine grape', 11),
  ('Mint', 'Water Mint', 'For ponds and teas', 8),
  ('Mint', 'Corsican Mint', 'Tiny mat ground cover', 9),
  ('Mint', 'Ginger Mint', 'Apple-mint hybrid', 10),
  ('Tomato', 'Cherokee Purple', 'Classic purple heirloom', 6),
  ('Tomato', 'Early Girl', 'Early slicer', 7),
  ('Tomato', 'Big Beef', 'Large hybrid slicer', 8),
  ('Tomato', 'Mortgage Lifter', 'Large pink heirloom', 9),
  ('Tomato', 'Rutgers', 'Classic NE tomato', 10),
  ('Tomato', 'Amish Paste', 'Heavy paste tomato', 11),
  ('Tomato', 'Green Zebra', 'Green striped heirloom', 12),
  ('Tomato', 'Celebrity', 'Reliable hybrid', 13),
  ('Tomato', 'Juliet', 'Prolific grape-type', 14),
  ('Blueberry', 'Duke', 'Early highbush; firm berries', 5),
  ('Blueberry', 'Elliott', 'Late-season highbush', 6),
  ('Blueberry', 'Patriot', 'Early; red fall color', 7),
  ('Blueberry', 'Chandler', 'Very large berries', 8),
  ('Blueberry', 'Top Hat', 'Compact patio blueberry', 9),
  ('Blueberry', 'Pink Lemonade', 'Pink-fruited blueberry', 10),
  ('Strawberry', 'Jewel', 'Midseason NE favorite', 5),
  ('Strawberry', 'Honeoye', 'Early heavy crop', 6),
  ('Strawberry', 'Sparkle', 'Classic NE June bearer', 7),
  ('Strawberry', 'Ozark Beauty', 'Everbearing classic', 8),
  ('Red Raspberry', 'Latham', 'Summer red raspberry', 5),
  ('Red Raspberry', 'Nova', 'Large firm berries', 6),
  ('Red Raspberry', 'Anne', 'Yellow everbearing', 7),
  ('Red Raspberry', 'Polana', 'Early fall bearing', 8),
  ('Rose', 'David Austin (English)', 'Old rose form; repeat bloom', 5),
  ('Rose', 'Mr. Lincoln', 'Dark red hybrid tea', 6),
  ('Rose', 'Peace', 'Yellow-pink classic', 7),
  ('Rose', 'Zephirine Drouhin', 'Climbing thornless', 8),
  ('Rose', 'Graham Thomas', 'Golden yellow English', 9),
  ('Rose', 'Double Knock Out', 'Double landscape rose', 10),
  ('Rose', 'Floribunda', 'Cluster-flower bush rose', 11),
  ('Rose', 'Grandiflora', 'Large-flower hybrid', 12),
  ('Rhododendron', 'Catawbiense Album', 'White catawba type', 5),
  ('Rhododendron', 'Purple Gem', 'Low purple; early bloom', 6),
  ('Rhododendron', 'Lee''s Dark Purple', 'Compact deep purple', 7),
  ('Rhododendron', 'Golden Oriole', 'Yellow rhododendron', 8),
  ('Rhododendron', 'Scintillation', 'Large pink trusses', 9),
  ('Rhododendron', 'Capistrano', 'Pale yellow NE hardy', 10),
  ('Iris', 'Immortality', 'Reblooming white bearded', 5),
  ('Iris', 'Caesar''s Brother', 'Siberian blue classic', 6),
  ('Iris', 'Beverly Sills', 'Pink bearded iris', 7),
  ('Iris', 'Stellar Lights', 'Bicolor bearded', 8),
  ('Iris', 'Purple Sensation', 'Dutch iris purple', 9),
  ('Iris', 'Jennifer Rebecca', 'Ruffled pink bearded', 10),
  ('Lily of the Valley', 'Hardwick Hall', 'Gold-edged leaves', 5),
  ('Lily of the Valley', 'Gertrude Jekyll', 'Strong fragrance', 6),
  ('Lily of the Valley', 'Green Tapestry', 'Variegated leaves', 7),
  ('Lily of the Valley', 'Bordeaux', 'Large fragrant bells', 8),
  ('Gladiola', 'Prins Claus', 'Pink and white bicolor', 5),
  ('Gladiola', 'Green Star', 'Lime green spikes', 6),
  ('Gladiola', 'Black Star', 'Deep purple-black', 7),
  ('Gladiola', 'Atom', 'Red with white edge', 8),
  ('Phlox', 'Laura', 'Purple garden phlox; mildew resistant', 5),
  ('Phlox', 'Bright Eyes', 'White eye pink phlox', 6),
  ('Phlox', 'Emerald Pink', 'Low creeping mounding', 7),
  ('Phlox', 'Flame White', 'Compact white garden', 8),
  ('Phlox', 'Purple Beauty', 'Creeping phlox purple', 9),
  ('Phlox', 'Robert Poore', 'Magenta garden phlox', 10),
  ('Daisies', 'Alaska', 'Large white Shasta', 5),
  ('Daisies', 'Crazy Daisy', 'Frilly Shasta type', 6),
  ('Daisies', 'Snow Lady', 'Compact white Shasta', 7),
  ('Daisies', 'Becky Improved', 'Taller Shasta selection', 8),
  ('Hosta', 'June', 'Blue center gold edge', 5),
  ('Hosta', 'Frances Williams', 'Blue with gold margin', 6),
  ('Hosta', 'Empress Wu', 'Giant blue hosta', 7),
  ('Hosta', 'Halcyon', 'Steel blue slow grower', 8),
  ('Hosta', 'Minuteman', 'White edged green', 9),
  ('Hosta', 'June Spirit', 'Gold and green', 10),
  ('Daylily', 'Catherine Woodbury', 'Large lavender-pink', 5),
  ('Daylily', 'Hyperion', 'Classic yellow fragrant', 6),
  ('Daylily', 'Stella Supreme', 'Double gold', 7),
  ('Daylily', 'Autumn Minaret', 'Tall late yellow', 8),
  ('Daylily', 'Frans Hals', 'Bicolor orange-red', 9),
  ('Daylily', 'Chicago Star', 'Red rebloomer', 10),
  ('Garden Peony', 'Coral Charm', 'Coral single peony', 5),
  ('Garden Peony', 'Do Tell', 'Soft pink fragrant', 6),
  ('Garden Peony', 'Krinkled White', 'White single', 7),
  ('Garden Peony', 'Duchess de Nemours', 'White double classic', 8),
  ('Foxglove', 'Pam''s Choice', 'Large white spikes', 5),
  ('Foxglove', 'Candy Mountain', 'Upward-facing pink', 6),
  ('Foxglove', 'Silver Fox', 'Compact white', 7),
  ('Foxglove', 'Polka Dot Purple', 'Spotted purple', 8),
  ('Panicle Hydrangea', 'Little Lime', 'Compact green-white', 5),
  ('Panicle Hydrangea', 'Pinky Winky', 'Two-tone pink-white', 6),
  ('Panicle Hydrangea', 'Bobo', 'Dwarf white panicles', 7),
  ('Panicle Hydrangea', 'Fire Light', 'Red aging panicles', 8),
  ('Purple Coneflower', 'PowWow Wild Berry', 'Compact purple', 5),
  ('Purple Coneflower', 'Tomahawk', 'Tall pink', 6),
  ('Purple Coneflower', 'Green Jewel', 'Green cone form', 7),
  ('Purple Coneflower', 'Paradiso Mix', 'Mixed color strain', 8),
  ('Black-Eyed Susan', 'Prairie Sun', 'Green-eyed bicolor', 5),
  ('Black-Eyed Susan', 'Rustic Colors', 'Mixed warm tones', 6),
  ('Black-Eyed Susan', 'Little Goldstar', 'Compact gold', 7),
  ('Black-Eyed Susan', 'Viette''s Little Suzy', 'Dwarf black-eyed Susan', 8),
  ('Lavender', 'Provence', 'Large fragrant lavender', 5),
  ('Lavender', 'Goodwin Creek Grey', 'Silvery foliage', 6),
  ('Lavender', 'Ellagance Purple', 'Compact deep purple', 7),
  ('Lavender', 'Thumbelina Leigh', 'Dwarf English', 8),
  ('Marigold', 'Bonanza', 'Mixed French marigold', 5),
  ('Marigold', 'Discovery', 'Orange African type', 6),
  ('Marigold', 'Lemon Gem', 'Signet yellow', 7),
  ('Marigold', 'Red Gem', 'Signet red', 8),
  ('Sunflower', 'Autumn Beauty', 'Mixed fall colors', 5),
  ('Sunflower', 'Italian White', 'Pale cream petals', 6),
  ('Sunflower', 'Sunrich Orange', 'Cut-flower hybrid', 7),
  ('Sunflower', 'ProCut Orange', 'Single-stem cut flower', 8),
  ('Basil', 'Osmin Purple', 'Dark purple basil', 9),
  ('Basil', 'Mrs. Burns Lemon', 'Intense lemon basil', 10),
  ('Basil', 'Spicy Globe', 'Compact globe basil', 11),
  ('Basil', 'Red Rubin', 'Deep red leaves', 12),
  ('Oregano', 'Golden', 'Gold variegated oregano', 5),
  ('Oregano', 'Kent Beauty', 'Ornamental hop-like', 6),
  ('Oregano', 'Compact Greek', 'Low dense Greek', 7),
  ('Oregano', 'Mexican Oregano', 'Warm-climate bold flavor', 8)
) AS v(catalog_name, name, description, sort_order)
  ON lower(c.common_name) = lower(v.catalog_name)
ON CONFLICT (plant_catalog_id, lower(name)) DO UPDATE SET
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
