-- Cultivar / subspecies options for all plant_catalog species

INSERT INTO plant_catalog_variety (plant_catalog_id, name, description, sort_order)
SELECT c.id, v.name, v.description, v.sort_order
FROM plant_catalog c
JOIN (VALUES
  ('Acorn Squash', 'Table Ace', 'Compact bush; classic acorn shape', 1),
  ('Acorn Squash', 'Honey Bear', 'Sweet; powdery mildew resistant', 2),
  ('Acorn Squash', 'Cream of the Crop', 'Cream-colored flesh', 3),
  ('Acorn Squash', 'Jet', 'Dark green; early maturing', 4),
  ('American Plum', 'Wild Native', 'Seedling from local wild stock', 1),
  ('American Plum', 'Princess', 'Selected wild plum with larger fruit', 2),
  ('American Plum', 'Stanley', 'European-type hybrid plum', 3),
  ('Arugula', 'Standard', 'Classic peppery salad rocket', 1),
  ('Arugula', 'Slow Bolt', 'Holds longer in summer heat', 2),
  ('Arugula', 'Astro', 'Mild flavor; fast growing', 3),
  ('Arugula', 'Wasabi', 'Spicy wasabi-like bite', 4),
  ('Asparagus', 'Mary Washington', 'Classic green asparagus', 1),
  ('Asparagus', 'Jersey Knight', 'All-male; high yield', 2),
  ('Asparagus', 'Purple Passion', 'Sweet purple spears', 3),
  ('Asparagus', 'Millennium', 'Cold-hardy NE favorite', 4),
  ('Astilbe', 'Fanal', 'Red plumes; compact', 1),
  ('Astilbe', 'Bridal Veil', 'White flowers; shade tolerant', 2),
  ('Astilbe', 'Visions', 'Compact pink; drought tolerant', 3),
  ('Astilbe', 'Maggie Daley', 'Lavender-pink; late bloom', 4),
  ('Autumn Joy Sedum', 'Autumn Joy', 'Classic pink-bronze fall blooms', 1),
  ('Autumn Joy Sedum', 'Autumn Fire', 'Deeper red flowers', 2),
  ('Autumn Joy Sedum', 'Matrona', 'Purple-tinged foliage', 3),
  ('Autumn Joy Sedum', 'Neon', 'Bright pink flowers', 4),
  ('Basil', 'Genovese', 'Classic Italian pesto basil', 1),
  ('Basil', 'Thai', 'Anise-scented; stir-fry herb', 2),
  ('Basil', 'Lemon', 'Citrus aroma; tea and fish', 3),
  ('Basil', 'Dark Opal', 'Purple leaves; ornamental', 4),
  ('Bee Balm', 'Jacob Cline', 'Large red; mildew resistant', 1),
  ('Bee Balm', 'Blue Stocking', 'Violet-blue flowers', 2),
  ('Bee Balm', 'Panorama Red Shades', 'Mixed red tones', 3),
  ('Bee Balm', 'Grand Parade', 'Compact purple', 4),
  ('Beet', 'Detroit Dark Red', 'Classic deep red root', 1),
  ('Beet', 'Golden', 'Yellow flesh; mild flavor', 2),
  ('Beet', 'Chioggia', 'Candy-striped interior', 3),
  ('Beet', 'Bull''s Blood', 'Dark leaves; baby greens', 4),
  ('Bell Pepper', 'California Wonder', 'Blocky green bell', 1),
  ('Bell Pepper', 'King Arthur', 'Large thick-walled', 2),
  ('Bell Pepper', 'Lunchbox Mix', 'Mini sweet peppers', 3),
  ('Bell Pepper', 'Carmen', 'Sweet Italian frying pepper', 4),
  ('Black Currant', 'Consort', 'Disease-resistant black currant', 1),
  ('Black Currant', 'Ben Sarek', 'Compact; heavy crop', 2),
  ('Black Currant', 'Crusader', 'White pine blister rust resistant', 3),
  ('Black-Eyed Susan', 'Goldsturm', 'Compact; long bloom', 1),
  ('Black-Eyed Susan', 'Indian Summer', 'Large golden flowers', 2),
  ('Black-Eyed Susan', 'Cherokee Sunset', 'Double bronze tones', 3),
  ('Black-Eyed Susan', 'American Gold Rush', 'Powdery mildew resistant', 4),
  ('Bleeding Heart', 'Old-Fashioned Pink', 'Classic arching pink hearts', 1),
  ('Bleeding Heart', 'Alba', 'White flowering form', 2),
  ('Bleeding Heart', 'Gold Heart', 'Golden foliage; pink flowers', 3),
  ('Bok Choy', 'Joi Choi', 'Standard white stem type', 1),
  ('Bok Choy', 'Mei Qing', 'Compact baby bok choy', 2),
  ('Bok Choy', 'Pak Choi', 'Full-size stir-fry type', 3),
  ('Bok Choy', 'Black Summer', 'Dark purple leaves', 4),
  ('Brandywine Tomato', 'Pink', 'Large pink heirloom', 1),
  ('Brandywine Tomato', 'Red', 'Red strain; rich flavor', 2),
  ('Brandywine Tomato', 'Yellow', 'Golden Brandywine', 3),
  ('Broccoli', 'Calabrese', 'Standard heading broccoli', 1),
  ('Broccoli', 'Belstar', 'Compact; heat tolerant', 2),
  ('Broccoli', 'Premium Crop', 'Large domed heads', 3),
  ('Broccoli', 'Purple Sprouting', 'Overwintering type', 4),
  ('Brussels Sprouts', 'Long Island Improved', 'Classic NE sprout', 1),
  ('Brussels Sprouts', 'Jade Cross', 'Compact; uniform', 2),
  ('Brussels Sprouts', 'Diablo', 'Red-tinged; cold sweet', 3),
  ('Brussels Sprouts', 'Churchill', 'Early maturing', 4),
  ('Butterfly Milkweed', 'Hello Yellow', 'Yellow flowers', 1),
  ('Butterfly Milkweed', 'Gay Butterflies', 'Mixed orange and yellow', 2),
  ('Butterfly Milkweed', 'Standard Orange', 'Native orange species', 3),
  ('Butterfly Milkweed', 'Western', 'Drought-tolerant form', 4),
  ('Butternut Squash', 'Waltham', 'Classic NE butternut', 1),
  ('Butternut Squash', 'Honeybaby', 'Compact; small fruit', 2),
  ('Butternut Squash', 'Burpee''s Butterbush', 'Bush habit', 3),
  ('Butternut Squash', 'JWS 6823', 'Improved storage', 4),
  ('Cantaloupe', 'Ambrosia', 'Sweet orange flesh', 1),
  ('Cantaloupe', 'Hale''s Best', 'Heirloom muskmelon', 2),
  ('Cantaloupe', 'Minnesota Midget', 'Short-season; small fruit', 3),
  ('Cantaloupe', 'Sarah''s Choice', 'Disease resistant', 4),
  ('Carrot', 'Nantes', 'Sweet blunt-root carrot', 1),
  ('Carrot', 'Danvers', 'Classic tapered NE carrot', 2),
  ('Carrot', 'Purple Haze', 'Purple skin; orange core', 3),
  ('Carrot', 'Scarlet Nantes', 'Early; tender', 4),
  ('Catmint', 'Walker''s Low', 'Low mounding; lavender blue', 1),
  ('Catmint', 'Six Hills Giant', 'Taller; gray foliage', 2),
  ('Catmint', 'Blue Wonder', 'Compact blue flowers', 3),
  ('Catmint', 'Little Trudy', 'Dwarf; reblooms', 4),
  ('Cauliflower', 'Snowball', 'White heading type', 1),
  ('Cauliflower', 'Cheddar', 'Orange beta-carotene rich', 2),
  ('Cauliflower', 'Graffiti', 'Purple heads', 3),
  ('Cauliflower', 'Romanesco', 'Spiral green heads', 4),
  ('Chamomile', 'German', 'Annual chamomile; tea herb', 1),
  ('Chamomile', 'Roman', 'Perennial ground cover', 2),
  ('Chamomile', 'Zloty Lan', 'Polish tea cultivar', 3),
  ('Cherry Tomato', 'Sungold', 'Sweet orange cherry', 1),
  ('Cherry Tomato', 'Sweet 100', 'Prolific red cherry', 2),
  ('Cherry Tomato', 'Black Cherry', 'Dark heirloom cherry', 3),
  ('Cherry Tomato', 'Yellow Pear', 'Teardrop yellow fruit', 4),
  ('Cherry Tree', 'Bing', 'Dark sweet cherry', 1),
  ('Cherry Tree', 'Rainier', 'Yellow-red sweet cherry', 2),
  ('Cherry Tree', 'Stella', 'Self-fertile sweet cherry', 3),
  ('Cherry Tree', 'Meteor', 'Sour pie cherry on dwarf root', 4),
  ('Chives', 'Common', 'Standard onion chives', 1),
  ('Chives', 'Garlic', 'Flat-leaf garlic chives', 2),
  ('Chives', 'Fine Leaf', 'Delicate garnish chives', 3),
  ('Cilantro', 'Slow Bolt', 'Lasts longer before flowering', 1),
  ('Cilantro', 'Cruiser', 'Large leaf; bolt resistant', 2),
  ('Cilantro', 'Leisure', 'Standard cilantro', 3),
  ('Cilantro', 'Delfino', 'Fine ferny leaves', 4),
  ('Collard Greens', 'Georgia', 'Classic Southern collard', 1),
  ('Collard Greens', 'Champion', 'Slow bolting', 2),
  ('Collard Greens', 'Flash', 'Smooth leaf; tender', 3),
  ('Collard Greens', 'Vates', 'Dwarf; cold hardy', 4),
  ('Common Sage', 'Berggarten', 'Broad silver leaves', 1),
  ('Common Sage', 'Purpurascens', 'Purple sage', 2),
  ('Common Sage', 'Tricolor', 'Variegated green and pink', 3),
  ('Common Sage', 'Icterina', 'Golden variegated', 4),
  ('Concord Grape', 'Standard Concord', 'Classic NE labrusca grape', 1),
  ('Concord Grape', 'Seedless Concord', 'Seedless juice grape', 2),
  ('Concord Grape', 'Fredonia', 'Early ripening Concord type', 3),
  ('Coral Bells', 'Palace Purple', 'Deep purple foliage', 1),
  ('Coral Bells', 'Fire Alarm', 'Bright red leaves', 2),
  ('Coral Bells', 'Citronelle', 'Chartreuse foliage', 3),
  ('Coral Bells', 'Obsidian', 'Near-black leaves', 4),
  ('Cranberry', 'Stevens', 'Standard commercial cranberry', 1),
  ('Cranberry', 'Howes', 'Native Massachusetts type', 2),
  ('Cranberry', 'Ben Lear', 'Early large berries', 3),
  ('Cranberry', 'Mullica Queen', 'Newer high-yield cultivar', 4),
  ('Creeping Thyme', 'Elfin', 'Tiny mat; walkable', 1),
  ('Creeping Thyme', 'Red Creeping', 'Crimson flowers', 2),
  ('Creeping Thyme', 'Magic Carpet', 'Lemon-scented ground cover', 3),
  ('Creeping Thyme', 'Woolly', 'Soft gray-green mat', 4),
  ('Cucumber', 'Marketmore', 'Standard slicer', 1),
  ('Cucumber', 'Straight Eight', 'Classic long cucumber', 2),
  ('Cucumber', 'Lemon', 'Round yellow heirloom', 3),
  ('Cucumber', 'Pickling (Boston)', 'Small pickling cukes', 4),
  ('Daylily', 'Stella de Oro', 'Reblooming gold', 1),
  ('Daylily', 'Pardon Me', 'Red rebloomer; compact', 2),
  ('Daylily', 'Happy Returns', 'Yellow rebloomer', 3),
  ('Daylily', 'Chicago Apache', 'Red single bloom', 4),
  ('Delicata Squash', 'Cornell''s Bush', 'Compact bush type', 1),
  ('Delicata Squash', 'Honey Boat', 'Extra sweet flesh', 2),
  ('Delicata Squash', 'Zeppelin', 'Uniform shape', 3),
  ('Delicata Squash', 'Sweet Dumpling', 'Small single-serving', 4),
  ('Dill', 'Bouquet', 'Standard dill for pickling', 1),
  ('Dill', 'Fernleaf', 'Compact; container friendly', 2),
  ('Dill', 'Mammoth', 'Large plants; seed harvest', 3),
  ('Dill', 'Dukat', 'Slow bolting; leafy', 4),
  ('Edamame', 'Butterbeans', 'Large green soybean', 1),
  ('Edamame', 'Envy', 'Early maturing edamame', 2),
  ('Edamame', 'Shirofumi', 'Sweet Japanese type', 3),
  ('Edamame', 'Midori Giant', 'Classic garden soybean', 4),
  ('Eggplant', 'Black Beauty', 'Standard purple globe', 1),
  ('Eggplant', 'Ichiban', 'Long Japanese type', 2),
  ('Eggplant', 'Rosa Bianca', 'Italian heirloom; mild', 3),
  ('Eggplant', 'Ping Tung', 'Long lavender fruit', 4),
  ('Elderberry', 'Adams', 'Standard American elderberry', 1),
  ('Elderberry', 'Johns', 'Companion pollinator for Adams', 2),
  ('Elderberry', 'York', 'Large berry clusters', 3),
  ('Elderberry', 'Nova', 'Compact; heavy producer', 4),
  ('Fennel', 'Florence', 'Bulbing fennel; finocchio', 1),
  ('Fennel', 'Zefa Fino', 'Reliable bulb fennel', 2),
  ('Fennel', 'Orion', 'Fast maturing bulb', 3),
  ('Fennel', 'Bronze', 'Ornamental bronze foliage', 4),
  ('Flat-Leaf Parsley', 'Italian Giant', 'Large flat-leaf parsley', 1),
  ('Flat-Leaf Parsley', 'Giant of Italy', 'Robust flavor', 2),
  ('Flat-Leaf Parsley', 'Moss Curled', 'Curly parsley type', 3),
  ('Flat-Leaf Parsley', 'Paramount', 'Slow bolting', 4),
  ('Fleabane', 'Standard Native', 'Native daisy fleabane', 1),
  ('Fleabane', 'Lynnhaven Carpet', 'Low spreading form', 2),
  ('Fleabane', 'White Lights', 'White flowering selection', 3),
  ('French Tarragon', 'Classic French', 'True French tarragon', 1),
  ('French Tarragon', 'Sativa', 'Standard culinary clone', 2),
  ('French Tarragon', 'Mexican (Tagetes)', 'Warm-climate substitute', 3),
  ('Garden Peony', 'Sarah Bernhardt', 'Pink double; classic', 1),
  ('Garden Peony', 'Karl Rosenfield', 'Red double', 2),
  ('Garden Peony', 'Festiva Maxima', 'White with red flecks', 3),
  ('Garden Peony', 'Bowl of Beauty', 'Pink with yellow center', 4),
  ('Gooseberry', 'Hinnonmaki Red', 'Red dessert gooseberry', 1),
  ('Gooseberry', 'Hinnonmaki Yellow', 'Sweet yellow fruit', 2),
  ('Gooseberry', 'Invicta', 'Mildew resistant green', 3),
  ('Gooseberry', 'Captivator', 'Thornless red', 4),
  ('Greek Oregano', 'Greek', 'Strong flavor; culinary', 1),
  ('Greek Oregano', 'Italian', 'Milder oregano', 2),
  ('Greek Oregano', 'Hot and Spicy', 'Peppery oregano', 3),
  ('Green Bean', 'Blue Lake', 'Pole bean; classic', 1),
  ('Green Bean', 'Provider', 'Bush bean; early', 2),
  ('Green Bean', 'Contender', 'Heat tolerant bush', 3),
  ('Green Bean', 'Kentucky Wonder', 'Heirloom pole bean', 4),
  ('Green Cabbage', 'Golden Acre', 'Early round cabbage', 1),
  ('Green Cabbage', 'Stonehead', 'Compact; holds well', 2),
  ('Green Cabbage', 'Late Flat Dutch', 'Storage cabbage', 3),
  ('Green Cabbage', 'Red Acre', 'Red-leaf cabbage', 4),
  ('Hardneck Garlic', 'Rocambole', 'Rich flavor; NE hardy', 1),
  ('Hardneck Garlic', 'Porcelain', 'Large cloves; strong', 2),
  ('Hardneck Garlic', 'Purple Stripe', 'Complex flavor', 3),
  ('Hardneck Garlic', 'Music', 'Popular Porcelain cultivar', 4),
  ('Highbush Cranberry', 'American Native', 'Standard viburnum trilobum', 1),
  ('Highbush Cranberry', 'Wentworth', 'Selected heavy fruiting', 2),
  ('Highbush Cranberry', 'Compactum', 'Dwarf form', 3),
  ('Honeycrisp Apple', 'Standard', 'Honeycrisp on semi-dwarf', 1),
  ('Honeycrisp Apple', 'M9 Dwarf', 'M9 rootstock; small tree', 2),
  ('Honeycrisp Apple', 'B.9 Dwarf', 'Very dwarf; patio tree', 3),
  ('Honeycrisp Apple', 'G.935', 'Disease-resistant rootstock', 4),
  ('Hosta', 'Blue Angel', 'Large blue leaves', 1),
  ('Hosta', 'Guacamole', 'Chartreuse; fragrant', 2),
  ('Hosta', 'Patriot', 'Green with white edge', 3),
  ('Hosta', 'Sum and Substance', 'Giant gold leaves', 4),
  ('Jalapeño Pepper', 'Early Jalapeño', 'Standard hot pepper', 1),
  ('Jalapeño Pepper', 'TAM Mild Jalapeño', 'Milder heat', 2),
  ('Jalapeño Pepper', 'Mucho Nacho', 'Large jalapeño', 3),
  ('Jalapeño Pepper', 'Purple Jalapeño', 'Dark purple fruit', 4),
  ('Kale', 'Lacinato', 'Dinosaur kale; tender', 1),
  ('Kale', 'Winterbor', 'Curly green kale', 2),
  ('Kale', 'Red Russian', 'Flat purple-veined', 3),
  ('Kale', 'Scarlet', 'Ornamental red kale', 4),
  ('Kohlrabi', 'Purple Vienna', 'Purple skin kohlrabi', 1),
  ('Kohlrabi', 'White Vienna', 'Light green standard', 2),
  ('Kohlrabi', 'Kossak', 'Large storage type', 3),
  ('Kohlrabi', 'Azur Star', 'Blue-purple heirloom', 4),
  ('Lavender', 'Hidcote', 'Compact English lavender', 1),
  ('Lavender', 'Munstead', 'Hardy; gray foliage', 2),
  ('Lavender', 'Phenomenal', 'Cold-hardy hybrid', 3),
  ('Lavender', 'Grosso', 'High oil; Provence type', 4),
  ('Leek', 'American Flag', 'Standard fall leek', 1),
  ('Leek', 'Lancelot', 'Early maturing', 2),
  ('Leek', 'Bandit', 'Winter hardy leek', 3),
  ('Leek', 'King Richard', 'Summer leek; fast', 4),
  ('Lemon Balm', 'Standard', 'Classic lemon balm', 1),
  ('Lemon Balm', 'Quedlinburger', 'High oil content', 2),
  ('Lemon Balm', 'Citronella', 'Strong lemon scent', 3),
  ('Lettuce', 'Buttercrunch', 'Butterhead lettuce', 1),
  ('Lettuce', 'Black Seeded Simpson', 'Looseleaf; early', 2),
  ('Lettuce', 'Romaine (Parris Island)', 'Crisp romaine', 3),
  ('Lettuce', 'Red Salad Bowl', 'Red looseleaf', 4),
  ('Lilac', 'Common Purple', 'Classic Syringa vulgaris', 1),
  ('Lilac', 'Miss Kim', 'Compact Korean lilac', 2),
  ('Lilac', 'President Grevy', 'Double blue flowers', 3),
  ('Lilac', 'Bloomerang', 'Reblooming lilac', 4),
  ('Marigold', 'French (Durango)', 'Compact French marigold', 1),
  ('Marigold', 'African (Crackerjack)', 'Large pom-pom blooms', 2),
  ('Marigold', 'Signet (Gem)', 'Edible tangerine gem', 3),
  ('Marigold', 'White Swan', 'White African marigold', 4),
  ('Montmorency Cherry', 'Standard', 'Classic sour pie cherry', 1),
  ('Montmorency Cherry', 'Meteor', 'Dwarf sour cherry', 2),
  ('Montmorency Cherry', 'North Star', 'Genetic dwarf pie cherry', 3),
  ('Montmorency Cherry', 'Surefire', 'Late-blooming sour', 4),
  ('Mullein', 'Common', 'Standard biennial mullein', 1),
  ('Mullein', 'Sixteen-Hundred', 'Selected ornamental', 2),
  ('Mullein', 'Southern', 'Native southern type', 3),
  ('New England Aster', 'Purple Dome', 'Compact purple', 1),
  ('New England Aster', 'Alma Potschke', 'Deep rose pink', 2),
  ('New England Aster', 'Harrington''s Pink', 'Tall pink native', 3),
  ('New England Aster', 'September Ruby', 'Ruby red flowers', 4),
  ('Ostrich Fern', 'Standard Native', 'Classic fiddlehead fern', 1),
  ('Ostrich Fern', 'Matteuccia', 'Thelypteris native type', 2),
  ('Ostrich Fern', 'King Ostrich', 'Selected vigor', 3),
  ('Panicle Hydrangea', 'Limelight', 'Green-white panicles', 1),
  ('Panicle Hydrangea', 'Quick Fire', 'Early white-pink', 2),
  ('Panicle Hydrangea', 'PeeGee', 'Classic panicle type', 3),
  ('Panicle Hydrangea', 'Vanilla Strawberry', 'Pink aging blooms', 4),
  ('Parsnip', 'Hollow Crown', 'Classic long parsnip', 1),
  ('Parsnip', 'All American', 'Smooth roots', 2),
  ('Parsnip', 'Gladiator', 'Canner type; uniform', 3),
  ('Parsnip', 'Javelin', 'Disease resistant', 4),
  ('Pawpaw', 'Sunflower', 'Selected pawpaw cultivar', 1),
  ('Pawpaw', 'Pennsylvania Golden', 'Early ripening', 2),
  ('Pawpaw', 'Allegheny', 'Large fruit; rich flavor', 3),
  ('Pawpaw', 'NC-1', 'Canadian hardy selection', 4),
  ('Pea', 'Sugar Snap', 'Edible-pod snap pea', 1),
  ('Pea', 'Wando', 'Heat tolerant shell pea', 2),
  ('Pea', 'Little Marvel', 'Compact shelling pea', 3),
  ('Pea', 'Oregon Sugar Pod', 'Snow pea type', 4),
  ('Purple Coneflower', 'Purple Coneflower', 'Standard Echinacea purpurea', 1),
  ('Purple Coneflower', 'Magnus', 'Large pink petals', 2),
  ('Purple Coneflower', 'White Swan', 'White coneflower', 3),
  ('Purple Coneflower', 'Cheyenne Spirit', 'Mixed color seed strain', 4),
  ('Radish', 'Cherry Belle', 'Round red spring radish', 1),
  ('Radish', 'French Breakfast', 'Oblong mild radish', 2),
  ('Radish', 'Watermelon', 'White skin; red interior', 3),
  ('Radish', 'Daikon (Miyashige)', 'Long white radish', 4),
  ('Red Currant', 'Red Lake', 'Standard red currant', 1),
  ('Red Currant', 'Rovada', 'Long trusses; late', 2),
  ('Red Currant', 'Wilder', 'Heavy producer', 3),
  ('Red Currant', 'Jonkheer van Tets', 'Early red currant', 4),
  ('Red Raspberry', 'Heritage', 'Everbearing red raspberry', 1),
  ('Red Raspberry', 'Boyne', 'Summer-bearing; hardy', 2),
  ('Red Raspberry', 'Caroline', 'Late everbearing', 3),
  ('Red Raspberry', 'Killarney', 'Firm fruit; disease resistant', 4),
  ('Red Twig Dogwood', 'Bailey', 'Selected red stems', 1),
  ('Red Twig Dogwood', 'Arctic Fire', 'Compact red twig', 2),
  ('Red Twig Dogwood', 'Cardinal', 'Bright winter color', 3),
  ('Red Twig Dogwood', 'Native Standard', 'Wild type dogwood', 4),
  ('Rhubarb', 'Victoria', 'Classic green-red stalks', 1),
  ('Rhubarb', 'Canada Red', 'Red stalks throughout', 2),
  ('Rhubarb', 'MacDonald', 'Tender early stalks', 3),
  ('Rhubarb', 'Valentine', 'Deep red; sweet', 4),
  ('Rosemary', 'Arp', 'Cold-hardy rosemary', 1),
  ('Rosemary', 'Tuscan Blue', 'Upright culinary', 2),
  ('Rosemary', 'Prostrate', 'Trailing rosemary', 3),
  ('Rosemary', 'Barbecue', 'Strong flavor for grilling', 4),
  ('Scallion', 'Evergreen Hardy White', 'Bunching onion', 1),
  ('Scallion', 'Ishikura', 'Long white scallion', 2),
  ('Scallion', 'Parade', 'Uniform scallion', 3),
  ('Scallion', 'Red Beard', 'Red-base scallion', 4),
  ('Serviceberry', 'Shadblow', 'Native Amelanchier', 1),
  ('Serviceberry', 'Autumn Brilliance', 'Selected heavy fruit', 2),
  ('Serviceberry', 'Regent', 'Saskatoon-type serviceberry', 3),
  ('Serviceberry', 'Smoky', 'Large sweet berries', 4),
  ('Spinach', 'Bloomsdale', 'Savoy leaf spinach', 1),
  ('Spinach', 'Space', 'Smooth leaf; bolt resistant', 2),
  ('Spinach', 'Tyee', 'Semi-savoy; mildew resistant', 3),
  ('Spinach', 'Giant Winter', 'Overwintering spinach', 4),
  ('Strawberry', 'Earliglow', 'Early June-bearing', 1),
  ('Strawberry', 'Allstar', 'Large midseason berry', 2),
  ('Strawberry', 'Seascape', 'Day-neutral everbearing', 3),
  ('Strawberry', 'Alpine (Mignonette)', 'Small intense berries', 4),
  ('Sugar Baby Watermelon', 'Standard', 'Classic icebox melon', 1),
  ('Sugar Baby Watermelon', 'Petite Treat', 'Mini personal melon', 2),
  ('Sugar Baby Watermelon', 'Yellow Doll', 'Yellow flesh icebox', 3),
  ('Sugar Baby Watermelon', 'New Hampshire Midget', 'Short season', 4),
  ('Sugar Pumpkin', 'Small Sugar', 'Classic pie pumpkin', 1),
  ('Sugar Pumpkin', 'Baby Pam', 'Uniform pie pumpkin', 2),
  ('Sugar Pumpkin', 'Winter Luxury', 'Fine-textured flesh', 3),
  ('Sugar Pumpkin', 'New England Pie', 'Heirloom NE pumpkin', 4),
  ('Sunflower', 'Mammoth', 'Giant single head', 1),
  ('Sunflower', 'Velvet Queen', 'Dark red petals', 2),
  ('Sunflower', 'Lemon Queen', 'Pollinator favorite', 3),
  ('Sunflower', 'Teddy Bear', 'Double dwarf sunflower', 4),
  ('Sweet Corn', 'Golden Bantam', 'Heirloom sweet corn', 1),
  ('Sweet Corn', 'Silver Queen', 'White sweet corn', 2),
  ('Sweet Corn', 'Peaches and Cream', 'Bicolor supersweet', 3),
  ('Sweet Corn', 'Trinity', 'Early bicolor', 4),
  ('Swiss Chard', 'Bright Lights', 'Rainbow stem chard', 1),
  ('Swiss Chard', 'Fordhook Giant', 'White stem; large leaves', 2),
  ('Swiss Chard', 'Ruby Red', 'Red stem chard', 3),
  ('Swiss Chard', 'Lucullus', 'Light green crumpled leaf', 4),
  ('Turnip', 'Purple Top White Globe', 'Classic turnip', 1),
  ('Turnip', 'Hakurei', 'Salad turnip; mild', 2),
  ('Turnip', 'Golden Ball', 'Yellow turnip', 3),
  ('Turnip', 'Seven Top', 'Greens type; no bulb', 4),
  ('Virginia Bluebell', 'Standard Native', 'Classic blue spring ephemeral', 1),
  ('Virginia Bluebell', 'Pink Form', 'Rare pink flowered form', 2),
  ('Virginia Bluebell', 'Alba', 'White flowering form', 3),
  ('Winterberry Holly', 'Red Sprite', 'Compact female; red berries', 1),
  ('Winterberry Holly', 'Berry Heavy', 'Heavy fruiting female', 2),
  ('Winterberry Holly', 'Jim Dandy', 'Male pollinator', 3),
  ('Winterberry Holly', 'Southern Gentleman', 'Male pollinator', 4),
  ('Yellow Onion', 'Yellow Sweet Spanish', 'Large storage onion', 1),
  ('Yellow Onion', 'Copra', 'Long keeper yellow', 2),
  ('Yellow Onion', 'Walla Walla', 'Sweet onion', 3),
  ('Yellow Onion', 'Stuttgarter', 'Standard yellow sets', 4),
  ('Yukon Gold Potato', 'Yukon Gold', 'Classic yellow potato', 1),
  ('Yukon Gold Potato', 'Kennebec', 'All-purpose white potato', 2),
  ('Yukon Gold Potato', 'Red Norland', 'Early red skin', 3),
  ('Yukon Gold Potato', 'Purple Majesty', 'Purple-flesh potato', 4),
  ('Zucchini', 'Black Beauty', 'Dark green zucchini', 1),
  ('Zucchini', 'Costata Romanesco', 'Ridged Italian type', 2),
  ('Zucchini', 'Golden', 'Yellow zucchini', 3),
  ('Zucchini', 'Eight Ball', 'Round zucchini', 4)
) AS v(catalog_name, name, description, sort_order)
  ON lower(c.common_name) = lower(v.catalog_name)
ON CONFLICT (plant_catalog_id, lower(name)) DO UPDATE SET
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
